module.exports = {
  plugins: [require("flowbite/plugin")],
  content: ["./node_modules/flowbite/**/*.js"],
  safelist: [
    "gap-[16px]",
    "border-[#EDEFF5]",
    "text-[#1A1A1D]",
    "my-[8px]",
    "px-[16px]",
    "py-[12px]",

    "mt-16",
    "mt-12",
    "text-2xl",
    "font-semibold",
    "mb-4",
    "text-lg",
    "font-medium",
    "mb-2",
    "list-disc",
    " space-y-1 ",
    "list-inside",
    "table-auto",
    " w-full",
    " text-sm ",
    "border ",
    "text-left",
  ],
};
